config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "positions#index"

  resources :positions do
    resources :candidates
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  include Hiring

  belongs_to :position
  has_one_attached :picture
  has_one_attached :cv
  has_many_attached :docs
  enum status: %w[applied test interview1 interview2 interview3 hired], _default: :applied

  validates :name, :email, :phone_number, :university, :gpa, :bio, :status, presence: true
  validates :phone_number, :gpa, numericality: true
  validates :email, :phone_number, uniqueness: true
end

app/models/concerns/hiring.rb
module Hiring
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[applied test interview1 interview2 interview3 hired]
  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end
end

app/models/position.rb
class Position < ApplicationRecord
  has_many :candidates, dependent: :destroy
  has_one_attached :logo
  default_scope { order(deadline: :asc) }

  validates :name, :description, :started_at, :ends_at, :vacancies, presence: true
  validates :vacancies, numericality: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
  before_action :set_position, only: [:show, :new, :create, :edit, :destroy]
  def show
    @candidate = @position.candidates.find(params[:id])
  end

  def new
    @candidate = @position.candidates.new
  end

  def create
    @candidate = @position.candidates.create(candidate_params)
    if @candidate.save
      redirect_to position_path(@position)
    else
      render :new
    end
  end

  def edit
    @candidate = @position.candidates.find(params[:id])
  end

  def update
    @candidate = Candidate.find(params[:id])
    if @candidate.update(candidate_params)
      redirect_to position_path(@candidate.position.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @candidate = @position.candidates.find(params[:id])
    @candidate.destroy!
    redirect_to position_path(@position)
  end

  private
  def candidate_params
    params.require(:candidate).permit(:name, :email, :phone_number, :university, :gpa, :bio, :status, :picture, :cv, docs: [])
  end

  def set_position
    @position = Position.find(params[:position_id])
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  def index
    @positions = Position.all
  end

  def show
  end

  def new
    @position = Position.new
  end

  def create
    @position = Position.new(position_params)
    if @position.save
      redirect_to @position
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @position.update(position_params)
      redirect_to @position
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @position.destroy
    redirect_to positions_path, status: :see_other
  end

  private
  def position_params
    params.require(:position).permit(:name, :description, :started_at, :ends_at, :vacancies, :logo)
  end

  def set_position
    @position = Position.find(params[:id])
  end
end

app/views/candidates/_form.html.erb
<%= form_with model: [ position, candidate ], data: { turbo: false } do |form| %>

  <div class="px-5 py-2 mx-5">
    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :name %></div>
      <%= form.text_field :name, required: true %>
      <% form.object.errors.full_messages_for(:name).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :email %></div>
      <%= form.text_field :email, required: true %>
      <% form.object.errors.full_messages_for(:email).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :phone_number %></div>
      <%= form.text_field :phone_number, required: true %>
      <% form.object.errors.full_messages_for(:phone_number).each do |message| %>
        <div class="error"><%= message %></div>
    <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :university %></div>
      <%= form.text_field :university, required: true %>
      <% form.object.errors.full_messages_for(:university).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :gpa %></div>
      <%= form.text_field :gpa, required: true %>
      <% form.object.errors.full_messages_for(:gpa).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :bio %></div>
      <%= form.text_area :bio, size: "100x5", required: true %>
      <% form.object.errors.full_messages_for(:bio).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :picture %></div>
      <%= form.file_field :picture, required: true %>
      <% form.object.errors.full_messages_for(:picture).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :cv %></div>
      <div><%= form.file_field :cv, required: true %></div>
      <% form.object.errors.full_messages_for(:cv).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :docs %></div>
      <div><%= form.file_field :docs, :multiple => true, required: true %></div>
      <% form.object.errors.full_messages_for(:docs).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <% if candidate.persisted? %>
      <div class="my-1">
        <div class="form-label fw-bold"><%= form.label :status %></div>
        <%= form.select :status, %w[applied test interview1 interview2 interview3 hired], selected: 'applied', required: true %>
        <% form.object.errors.full_messages_for(:status).each do |message| %>
          <div class="error"><%= message %></div>
        <% end %>
      </div>
    <% end %>

    <button class="my-3 btn btn-primary">
      <%= form.submit :class => "btn" %>
    </button>
<% end %>
</div>

app/views/candidates/edit.html.erb
<div class="mb-5"><%= render "positions/header" %></div>
<h1 class="display-5 text-center m-3">Edit Candidate</h1>
<%= render "candidates/form", position: @position, candidate: @candidate %>

app/views/candidates/new.html.erb
<div class="mb-5"><%= render "positions/header" %></div>
<h1 class="display-5 text-center m-3">New Candidate</h1>
<%= render "candidates/form", position: @position, candidate: @candidate %>

app/views/candidates/show.html.erb
<div class="mb-5"><%= render "positions/header" %></div>
<h1 class="display-5 text-center m-3">Candidate Details</h1>

<div class="mx-auto">
  <div class="card mx-5 my-3 p-2">
    <div class="card-body">

      <% if @candidate.picture.attached? %>
        <div class="text-center"><%= image_tag @candidate.picture, width: "10%", height: "10%" %></div>
      <% end %>

      <h1 class="card-title text-center"><%= @candidate.name %></h1>

      <div class="card text-center p-2 candidate-info">
        <div class="card-body">
          <h3 class="card-text"><strong>Email: </strong><%= @candidate.email %></h3>
          <h3 class="card-text"><strong>Phone Number: </strong><%= @candidate.phone_number %></h3>
          <h3 class="card-text"><strong>University: </strong><%= @candidate.university %></h3>
          <h3 class="card-text"><strong>GPA: </strong><%= @candidate.gpa %></h3>
          <h3 class="card-text"><strong>Status: </strong><%= @candidate.status %></h3>
          <h3 class="card-text text-start"><strong>Bio: </strong><%= @candidate.bio %></h3>
        </div>
      </div>

      <div class="container add-border p-5">
        <div class="row">
          <div class="col-3">
            <% if @candidate.cv.attached? %>
              <%= image_tag @candidate.cv, width: "100%", height: "100%", :class => "add-border" %>
              <%= link_to 'View CV', rails_blob_path(@candidate.cv, disposition: "preview", :class => "link-alt") %>
            <% end %>
          </div>
          <div class="col-9">
            <% if @candidate.docs.attached? %>
              <div>
                <% @candidate.docs.each do |doc| %>
                  <%= image_tag doc, :class => "add-border" %>
                  <%= link_to 'View Doc', rails_blob_path(doc, disposition: "preview", :class => "link-alt") %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <br>
      <div class="text-center my-3">
        <%= link_to "Edit Candidate", edit_position_candidate_path(@position.id, @candidate.id), :class => "link-alt" %>
        <%= link_to "Delete Candidate", [@position, @candidate], data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, :class => "link-alt" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hr Portal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_include_tag "turbo", type: "module" %>
  </head>

  <body>
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>

    <h1 class="display-1 text-center bg py-2 m-0">HR Portal</h1>
    <%= yield %>
  </body>
</html>

app/views/positions/_form.html.erb
<div class="px-5 py-2 mx-5">
  <%= form_with model: position do |form| %>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :name %></div>
      <div><%= form.text_field :name, size: "30x1", required: true  %></div>
      <% position.errors.full_messages_for(:name).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :description %></div>
      <div><%= form.text_area :description, size: "100x5", required: true %></div>
      <% position.errors.full_messages_for(:description).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :started_at %></div>
      <div><%= form.date_select :started_at, required: true %></div>
      <% position.errors.full_messages_for(:date_started_at).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :ends_at %></div>
      <div><%= form.date_select :ends_at, required: true %></div>
      <% position.errors.full_messages_for(:ends_at).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :vacancies %></div>
      <div><%= form.text_field :vacancies, size: "10x1", required: true  %></div>
      <% position.errors.full_messages_for(:vacancies).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <div class="my-1">
      <div class="form-label fw-bold"><%= form.label :logo %></div>
      <div><%= form.file_field :logo, required: true %></div>
      <% position.errors.full_messages_for(:logo).each do |message| %>
        <div class="error"><%= message %></div>
      <% end %>
    </div>

    <button class="my-3 btn btn-primary">
      <%= form.submit :class => "btn" %>
    </button>

  <% end %>
</div>

app/views/positions/_header.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark text-center">
  <div class="container-fluid">
    <div class="collapse navbar-collapse center-nav p-2">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link nav-item"><%= link_to "Home", root_path, :class => "link"%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-item"><%= link_to "New Position", new_position_path, :class => "link" %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-item"><%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, :class => "link" %></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/positions/_nav.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link"><%= link_to "Home", root_path, :class => "link"%></a>
          <span>  |  </span>
        </li>
        <li class="nav-item">
          <a class="nav-link"><%= link_to "Edit Position Details", edit_position_path(@position), :class => "link" %></a>
          <span>  |  </span>
        </li>
        <li class="nav-item">
          <a class="nav-link"><%= link_to "Delete Position", position_path(@position), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, :class => "link" %></a>
          <span>  |  </span>
        </li>
        <li class="nav-item">
          <a class="nav-link"><%= link_to "Create New Candidate",  new_position_candidate_path(@position), :class => "link" %></a>
          <span>  |  </span>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/positions/_nav1.html.erb
<nav class="navbar navbar-expand navbar-dark bg-dark text-center">
  <div class="container-fluid">
    <div class="collapse navbar-collapse center-nav p-2">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link nav-item"><%= link_to "Home", root_path, :class => "link"%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-item"><%= link_to "New Position", new_position_path, :class => "link" %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-item"><%= link_to "New Candidate",  new_candidate_path, :class => "link" %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-item"><%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, :class => "link" %></a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/positions/edit.html.erb
<div class="mb-5"><%= render "positions/header" %></div>
<h1 class="display-5 text-center m-2">Edit Position Details</h1>
<%= render "positions/form", position: @position %>

app/views/positions/index.html.erb
<div class="mb-5"><%= render "positions/header" %></div>
<h1 class="display-5 text-center mb-5">Current Job Openings</h1>

<div class="d-block mx-auto">
  <% @positions.each do |position| %>
    <div class="card mx-5 my-3 p-2 d-inline-flex h-100" style="width: 43%;">
      <div class="card-body">
        <% if position.logo.attached? %>
          <div class="p-3"><%= image_tag position.logo, width: "15%", height: "7%" %></div>
        <% end %>
        <h5 class="card-title"><%= link_to position.name, position %></h5>
        <p class="card-text"><%= position.description %></p>
        <p class="card-text fw-bold">Start Date: <%= position.started_at.strftime("%d/%m/%Y") %></p>
        <p class="card-text fw-bold">End Date: <%= position.ends_at.strftime("%d/%m/%Y") %></p>
        <p class="card-subtitle fw-bold">Positions: <%= position.vacancies %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/positions/new.html.erb
<div class="mb-5"><%= render "positions/header" %></div>
<h1 class="display-5 text-center m-3">New Position</h1>
<%= render "positions/form", position: @position %>

app/views/positions/show.html.erb
<div class="mb-2"><%= render "positions/header" %></div>
<div class="mx-5">
  <div class="p-3"> <%= image_tag @position.logo, width: "10%", height: "5%" %> </div>
  <h1 class="h1"> <%= @position.name %></h1>
  <p class="lead"> <strong>Description: </strong><%= @position.description %></p>
  <p class="lead"> <strong>Start Date: </strong><%= @position.started_at.strftime("%d/%m/%Y") %></p>
  <p class="lead"> <strong>End Date: </strong><%= @position.ends_at.strftime("%d/%m/%Y") %></p>
  <p class="lead"> <strong>Available Openings: </strong><%= @position.vacancies %></p>
  <hr>
  <a class=""><%= link_to "Edit Position Details", edit_position_path(@position), :class => "link-alt" %></a>
  <a class=""><%= link_to "Delete Position", position_path(@position), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, :class => "link-alt" %></a>
</div>

<hr>

<div class="mx-5">
  <div class="container mx-0 border-0">
    <div class="row">
      <div class="col-2">
        <h3 class="me-5">Candidates:  </h3>
      </div>
      <div class="col-10">
        <div class="me-5"><%= link_to "New Candidate",   new_position_candidate_path(@position), :class => "link-alt" %></div>
      </div>
    </div>
  </div>

  <hr>

  <div class="mx-auto">
    <% @position.candidates.each do |candidate| %>
      <div class="card mx-5 my-3 p-2 d-inline-flex h-100" style="display: inline-block; width: 40%;">
        <div class="card-body">
          <h5 class="card-title"><%= link_to candidate.name, position_candidate_path(@position, candidate) %></h5>
          <p class="card-text"><strong>Email: </strong><%= candidate.email %></p>
          <p class="card-text"><strong>Phone Number: </strong><%= candidate.phone_number %></p>
          <p class="card-text"><strong>University: </strong><%= candidate.university %></p>
          <p class="card-text"><strong>GPA: </strong><%= candidate.gpa %></p>
          <p class="card-text"><strong>Status: </strong><%= candidate.status %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>